### ISSUE TITLE
Problema de concatenação do pi

### ISSUE THREAD

**Issue by LeoAntunesBrombilla** [gmarcon83/Projeto-JS#1]
Olá pessoal, o pi está concatenando quando colocamos depois de um número. Passsamos pelo mesmo problema, para resolver criamos uma função que checa quando há um valor anterior e se há um valor anterior ele multiplica como é feito em algumas calculadoras.

![Screenshot from 2021-03-19 13-33-32](https://user-images.githubusercontent.com/76003107/111813393-e9edca80-88b7-11eb-8811-d1fd44127675.png)

**Comment by gmarcon83** [comment]
Resolvido com o #2
